export const Message = {
  invalidOtp: "Invalid OTP code.",
  otpExpired: "OTP code has expired.",
  userNotFound: "User does not exist.",
  userDashboardFetched: "User dashboard fetched successfully.",
  notAuthorized: "You are not authorized to access this resource.",
  userFound: "User already exists",
  invalidPassword: "The password provided is invalid",
  passwordIsSameAsOld: "New password cannot be the same as old your password",
  oldPasswordNotCorrect: "Old password is not correct",
  usernameAlreadyInUse: "Username is already in use",
  phoneExists: "The phone number already exists",
  phoneVerified: "The phone number is already verified",
  profilePicUpdated: "Profile picture set successfully.",
  phoneNumberAdded: "Phone number added. An OTP has been sent to your phone, kindly verify.",
  phoneOtpSent: "An OTP has been sent to your phone, kindly verify.",
  phoneNumberVerified: "Phone number verified successfully.",
  userAddressUpdated: "Address updated successfully.",
  userProfileUpdated: "User profile updated successfully.",
  postCreated: "Post created successfully",
  postUpdated: "Post updated successfully",
  postFetched: "Post fetched successfully",
  postDeleted: "Post deleted successfully",
  postNotFound: "Post not found.",
  communitySlugAlreadyInUse: "Community slug is already in use",
  communityDoesNotExist: "Community does not exit",
  leaderBoardFetched: "Leader board fetched successfully.",
  userRankFetched: "User rank fetched successfully.",
  userPointHistoryFetched: "User point history fetched successfully.",
  pointHistoryFetched: "Point history fetched successfully.",
  alreadyReferred: "You have been referred already.",
  referralCodeGenerated: "Referral code generated successfully.",
  referralCodeNotGenerated: "You cannot generate a referral code, you must have at least 50 points.",
  referrerUserDetailsFetched: "Referrer fetched successfully.",
  notReferred: "You were not referred by any user.",
  userReferralsFetched: "Referrals fetched successfully.",
  walletNotFound: "Wallet not found",
};
